defaults:
  - data: audioset20k_finetune
  - data_augm: cav_augm
  - backbone: cav
  - criterion: va_cls
  - optim: adam
  - train_algo: finetune
  - cl_algo: finetune
  - environment: default
  - hydra: default
  - logging: default
